import { app, BrowserWindow, ipcMain, shell } from "electron";
import path from "path";

// import { showMenu } from "./electron";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = (): void => {
  mainWindow = new BrowserWindow({
    title: "Лабораторная работа",
    height: 880,
    width: 1120,
    minWidth: 1024,
    icon: "./public/assets/icon.png",
    minHeight: 800,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: true,
      webSecurity: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.removeMenu();
  // showMenu();
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

ipcMain.on("openWorkTrip", () => {
  shell.openPath(path.join(__dirname, "../renderer/files/trip.docx"));
});

ipcMain.on("openMaterial", () => {
  shell.openPath(path.join(__dirname, "../renderer/files/info.docx"));
});

ipcMain.on("openMeth", () => {
  shell.openPath(path.join(__dirname, "../renderer/files/meth.docx"));
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
